---

- name: Install ruby and dependencies
  hosts: production
  remote_user: scot
  sudo: yes

  vars:
    rbenv:
      env: user
      version: v0.4.0
      ruby_version: 2.0.0-p481

  roles:
    - bakins.runit
    - git
    - nginx
    - users
    - sudo
    - role: zzet.rbenv
      rbenv_users:
        - deploy
    - DavidWittman.redis
    - pjan.vandaele.postgresql
    - deploy

