---

- name: Install Nginx
  apt: name=nginx state=present
  sudo: true

- copy: src=dev-server-api.conf dest=/etc/nginx/conf.d/dev-server-api.conf owner=root group=root mode=644
- file: path=/etc/nginx/sites-enabled/default state=absent

- name: Create WWW directory
  file: 'path=/var/www/ state=directory mode=0755'
  sudo: true

- name: Start Nginx
  service: name=nginx enabled=yes state=started
  sudo: true
  notify: started_nginx

