---

- name: Install Nginx
  apt: name=nginx state=present
  sudo: true

- name: Create WWW directory
  file: 'path=/var/www/ state=directory mode=0755'
  sudo: true

- name: Start Nginx
  service: name=nginx enabled=yes state=started
  sudo: true
  notify: started_nginx

